name:               "柚子"
description:        "Welcome to youzi's blog!"

url:                "https://zxyouzi.github.io"
author:             "柚子"
email:              "281151582@qq.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            ""
email:              "281151582@qq.com"
github:             "https://zxyouzi.github.io"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "柚子"

background:         "/img/background.jpg"
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname:
disqus_shortname:

# gitment
comment_gitment_repo: zxyouzi.github.io
comment_gitment_clientId: c760d643594d1c8977ba
comment_gitment_clientSecret: 4289dbd3d3ca67d042799d0f66c8a6a9695fb87c

markdown:           kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

nav:
  - name:           " Home"
    href:           "/"

  - name:           " Collections"
    href:           "/page/collections"
    
  - name:           " WatchTV"
    href:           "/page/watchtv"

  - name:           "StudySource"
    href:           "/page/studysource"

  - name:           "College"
    href:           "/page/colleage"
    
  - name:           "About"
    href:           "/about"
  

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

#原来的
#gems:
#  - jekyll-paginate
# paginate
plugins: [jekyll-paginate]
paginate: 5
port: 4000