name:               "柚子"
description:        "Welcome to youzi's blog!"

url:                "https://zxyouzi.github.io"
author:             "柚子"
email:              "281151582@qq.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            ""
email:              "281151582@qq.com"
github:             "https://zxyouzi.github.io"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "柚子"

background:         "/img/background.jpg"
paginate:           5
paginate_path:      "/page:num/"

baseurl:            "https://zxyouzi.github.io"
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           " Categories"
    href:           "/categories"
  - name:           " Collections"
    href:           "/page/collections"
  - name:           "Archives"
    href:           "/archives"
  - name:           "About"
    href:           "/about"
  

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate