name:               "柚子的blog"
description:        "Welcome to youzi's blog!"

url:                ""
author:             "柚子"
email:              "281151582@qq.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            ""
email:              "281151582@qq.com"
github:             "http://zxyouzi.github.io"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "柚子"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate